--- 
- name: Install IIS
  win_feature:
      name: "Web-Server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes

- name: Create temp folder to deploy
  win_file: path="C:\AULAUTIL" state=directory

