- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  roles:
  - create-instance

- hosts: launched
  gather_facts: true
  user: ec2-user
  become_user: root
  become: yes
  roles :
  - base

