  - name: ec2 group aulautil
    ec2_group:
     name: aulautil-win
     description: Prod:Infraestructura
     #vpc_id: vpc-id
     region: us-east-1
     rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 5986 
        to_port: 5986
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3389
        to_port: 3389
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
     rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  - name: run instance
    ec2:
     key_name: aulautil
     instance_type: t2.micro
     image: ami-fc97a7eb
     wait: yes
     group: aulautil-win
     wait_timeout: 500
     count: 1
     #vpc_subnet_id: subnet-c0673999
     instance_tags:
       Name: aulautil-win
       Service: windows
       Alias: a1a1
       Env: developing
       Product: infraestructura 
     region: us-east-1
     user_data: "{{ user_data }}"
     volumes:
       - device_name: /dev/xvda
         volume_size: 20
         delete_on_termination: true
       #- device_name: /dev/xvdh
       #  volume_size: 20
       #- device_name: /dev/xvdf
       #  volume_size: 100
    register: ec2
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    with_items: "{{ ec2.instances }}"
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 5986
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"

